<?php

namespace ContainerOVJMVvQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5duzfx9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5duzfx9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5duzfx9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'filmRepository' => ['privates', 'App\\Repository\\FilmRepository', 'getFilmRepositoryService', true],
            'filmcategoryRepository' => ['privates', 'App\\Repository\\FilmCategoryRepository', 'getFilmCategoryRepositoryService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'filmRepository' => 'App\\Repository\\FilmRepository',
            'filmcategoryRepository' => 'App\\Repository\\FilmCategoryRepository',
        ]);
    }
}
