<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPF8rjiu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPF8rjiu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPF8rjiu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPF8rjiu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPF8rjiu\App_KernelDevDebugContainer([
    'container.build_hash' => 'PF8rjiu',
    'container.build_id' => '25c27e43',
    'container.build_time' => 1681773654,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPF8rjiu');
