<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOVJMVvQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOVJMVvQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOVJMVvQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOVJMVvQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOVJMVvQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'OVJMVvQ',
    'container.build_id' => '0da7ef1d',
    'container.build_time' => 1681776859,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOVJMVvQ');
