<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW8sOJnZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW8sOJnZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW8sOJnZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW8sOJnZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW8sOJnZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'W8sOJnZ',
    'container.build_id' => 'd31be198',
    'container.build_time' => 1681676101,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW8sOJnZ');
